# GEMINI
gemini:
  distance: hellinger
  ovo: true

result_path: ../GEMINI/results/mesa/lenet5
data_path: ../GEMINI/data

# Dataset
dataset: ../GEMINI/data/custom_datasets/mesa_hr.py
dataset_kwargs:
similarity_fct:
similarity_kwargs:

use_cuda: false

# Regularisation
regularisations:
  entropy_weight: 0.0
  vat_weight: 0
  vat_kwargs:
    xi: 10.0
    eps: 1.0
  reconstruction_weight: 0.0

# Model
model:
  encoder: ../GEMINI/models/custom_models/encoder_lenet5_variation.py
  encoder_kwargs:
  clustering_head: ../GEMINI/models/custom_models/clustering_head_linear.py
  clustering_head_kwargs:
    input_shape: 84
    num_clusters: 6

  

# Training
epochs: 500
optimiser: adam
learning_rate: 0.001
batch_size: 250
num_workers: 16

# Evaluation
metrics:
  ari: on
  accuracy: on
  purity: on
  used_clusters: on